PROCEDURE menupv
SET SYSMENU TO

DEFINE PAD mmenu_1 OF _MSYSMENU PROMPT '\<ÐÀÁÎÒÀ Ñ ÊÌÑ' COLOR SCHEME 3 KEY ALT+A , ""
DEFINE PAD mmenu_2 OF _MSYSMENU PROMPT '\<ÇÀÏÐÎÑÛ Ê ÅÐÇ' COLOR SCHEME 3 KEY ALT+B , ""
DEFINE PAD mmenu_3 OF _MSYSMENU PROMPT '\<ÎÒ×ÅÒÛ' COLOR SCHEME 3 KEY ALT+E , ""
DEFINE PAD mmenu_4 OF _MSYSMENU PROMPT '\<SQL' COLOR SCHEME 3 KEY ALT+E , ""
DEFINE PAD mmenu_5 OF _MSYSMENU PROMPT '\<SQL BROKER' COLOR SCHEME 3 KEY ALT+E , ""
ON PAD mmenu_1 OF _MSYSMENU ACTIVATE POPUP popVvod
ON PAD mmenu_2 OF _MSYSMENU ACTIVATE POPUP popErz
ON PAD mmenu_3 OF _MSYSMENU ACTIVATE POPUP popOtchet
ON PAD mmenu_4 OF _MSYSMENU ACTIVATE POPUP popSQL
ON PAD mmenu_5 OF _MSYSMENU ACTIVATE POPUP popBroker

DEFINE POPUP popSQL MARGIN RELATIVE SHADOW COLOR SCHEME 4
DEFINE BAR 01 OF popSQL PROMPT 'ÈÌÏÎÐÒ Â ÁÄ SQL' PICTURE 'DATABASE.ICO'
DEFINE BAR 02 OF popSQL PROMPT '\-' PICTURE 'DATABASE.ICO'
DEFINE BAR 03 OF popSQL PROMPT 'ÑÎÇÄÀÍÈÅ BACKUP ÁÄ' PICTURE 'DATABASE.ICO'
DEFINE BAR 04 OF popSQL PROMPT 'SQL Sever Broker' PICTURE 'DATABASE.ICO'
ON SELECTION BAR 01 OF popSQL DO kms2sql3
ON SELECTION BAR 03 OF popSQL DO MakeBackUp
ON SELECTION BAR 04 OF popSQL DO SqlBroker

DEFINE POPUP popBroker MARGIN RELATIVE SHADOW COLOR SCHEME 4
DEFINE BAR 01 OF popBroker PROMPT 'START BROKER KMS' PICTURE 'DATABASE.ICO'
DEFINE BAR 02 OF popBroker PROMPT 'START DIALOG' PICTURE 'DATABASE.ICO'
DEFINE BAR 03 OF popBroker PROMPT 'RESERV' SKIP 
DEFINE BAR 04 OF popBroker PROMPT 'RESERV' SKIP 
DEFINE BAR 05 OF popBroker PROMPT 'CHECK QUEUE MICHAEL' PICTURE 'DATABASE.ICO'
DEFINE BAR 06 OF popBroker PROMPT 'CHECK QUEUE OLGA' PICTURE 'DATABASE.ICO'
DEFINE BAR 07 OF popBroker PROMPT 'RESERV' SKIP 
DEFINE BAR 08 OF popBroker PROMPT 'END DIALOGS' PICTURE 'DATABASE.ICO'
DEFINE BAR 09 OF popBroker PROMPT 'SHOW DIALOGS' PICTURE 'DATABASE.ICO'
DEFINE BAR 10 OF popBroker PROMPT 'STOP BROKER KMS' PICTURE 'DATABASE.ICO'
ON SELECTION BAR 01 OF popBroker DO StartBroker
ON SELECTION BAR 02 OF popBroker DO StartDialog
ON SELECTION BAR 05 OF popBroker DO CheckMicQueue
ON SELECTION BAR 06 OF popBroker DO CheckOlgaQueue
ON SELECTION BAR 08 OF popBroker DO EndDialogs
ON SELECTION BAR 09 OF popBroker DO ShowDialogs
ON SELECTION BAR 10 OF popBroker DO StopBroker

DEFINE POPUP popVvod MARGIN RELATIVE SHADOW COLOR SCHEME 4
DEFINE BAR 01 OF popVvod PROMPT 'ÐÅÃÈÑÒÐ ÇÀÑÒÐÀÕÎÂÀÍÍÛÕ' PICTURE 'DATABASE.ICO'
DEFINE BAR 02 OF popVvod PROMPT '\-'
DEFINE BAR 03 OF popVvod PROMPT 'ÏÎÈÑÊ ÏÎ ÍÎÌÅÐÍÈÊÓ' KEY ALT+N, "ALT+N"
DEFINE BAR 04 OF popVvod PROMPT 'ÏÎÈÑÊ ÏÎ ÑÒÎÏ-ËÈÑÒÓ' KEY ALT+S, "ALT+S"
DEFINE BAR 05 OF popVvod PROMPT 'ÏÎÈÑÊ ÏÎ ÂÑÅÌ ÁÀÇÀÌ' KEY ALT+Z, "ALT+Z"
DEFINE BAR 06 OF popVvod PROMPT '\-'
DEFINE BAR 07 OF popVvod PROMPT 'ÀÐÕÈÂÈÐÎÂÀÍÈÅ ÄÀÍÍÛÕ'
DEFINE BAR 08 OF popVvod PROMPT 'ÏÅÐÅÈÍÄÅÊÑÀÖÈß ÁÄ ÏÂ' SKIP FOR kol_pv!=1
DEFINE BAR 09 OF popVvod PROMPT '\-'
DEFINE BAR 10 OF popVvod PROMPT 'ÑÏÐÀÂÎ×ÍÈÊ ÏÎËÜÇÎÂÀÒÅËÅÉ'
DEFINE BAR 11 OF popVvod PROMPT 'ÑÏÐÀÂÎ×ÍÈÊ "ÌÅÑÒÎ ÐÀÁÎÒÛ"'
DEFINE BAR 12 OF popVvod PROMPT 'ÑÏÐÀÂÎ×ÍÈÊ ÏÐÅÄÏÐÈßÒÈÉ'
DEFINE BAR 13 OF popVvod PROMPT '\-'
DEFINE BAR 14 OF popVvod PROMPT 'ÂÛÕÎÄ' PICTURE 'CLOSE.BMP' KEY ALT+F4, "ALT+F4"

ON SELECTION BAR 01 OF popVvod DO FORM IIF(m.IsSQL, 'v_sql', 'v_kms')
ON SELECTION BAR 03 OF popVvod DO FORM FndOutS
ON SELECTION BAR 04 OF popVvod DO FORM FndStopList
ON SELECTION BAR 05 OF popVvod DO FORM FndAllBases
ON SELECTION BAR 07 OF popVvod DO ArcData
ON SELECTION BAR 08 OF popVvod OneBaseReind()
ON SELECTION BAR 10 OF popVvod DO FORM SprUsers 
ON SELECTION BAR 11 OF popVvod DO FORM SprWrkPl
ON SELECTION BAR 12 OF popVvod DO FORM SprPlants
ON SELECTION BAR 14 OF popVvod CLEAR EVENTS

DEFINE POPUP popErz MARGIN RELATIVE SHADOW COLOR SCHEME 4
DEFINE BAR 1 OF popErz PROMPT 'ÈÏ ÑÂÅÐÊÀ-5' PICTURE 'DATABASE.ICO'
DEFINE BAR 2 OF popErz PROMPT 'ÈÏ ÑÂÅÐÊÀ-6' PICTURE 'DATABASE.ICO'
DEFINE BAR 3 OF popErz PROMPT '\-'
DEFINE BAR 4 OF popErz PROMPT 'ÇÀÑÒÐÀÕÎÂÀÍÍÛÅ ÑÂÅÐÊÀ-5' PICTURE 'DATABASE.ICO'
DEFINE BAR 5 OF popErz PROMPT 'ÇÀÑÒÐÀÕÎÂÀÍÍÛÅ ÑÂÅÐÊÀ-6' PICTURE 'DATABASE.ICO'
ON SELECTION BAR 1 OF popErz DO FORM ViewIPs                   
ON SELECTION BAR 2 OF popErz DO FORM ViewIPs6
ON SELECTION BAR 4 OF popErz DO FORM ViewPaz                        
ON SELECTION BAR 5 OF popErz DO FORM ViewPaz6

DEFINE POPUP popOtchet MARGIN RELATIVE SHADOW COLOR SCHEME 4
DEFINE BAR 01 OF popOtchet PROMPT 'ÆÓÐÍÀË ÍÅÂÎÑÒÐÅÁÎÂÀÍÍÛÕ ÏÎËÈÑÎÂ' 
DEFINE BAR 02 OF popOtchet PROMPT 'ÆÓÐÍÀË ÍÅÂÎÑÒÐÅÁÎÂÀÍÍÛÕ ÏÎËÈÑÎÂ (Ñ ÂÛÁÎÐÎÌ)' 
DEFINE BAR 03 OF popOtchet PROMPT 'ÎÒ×ÅÒ ÏÎ "ÏÎÒÅÐßÍÍÛÌ" ÂÐÅÌßÍÊÀÌ'
ON SELECTION BAR 01 OF popOtchet DO NonDemandedEnp
ON SELECTION BAR 02 OF popOtchet DO NonDemandedEnp2
ON SELECTION BAR 03 OF popOtchet DO RepEmpVS

SET SYSMENU AUTOMATIC
SET SYSMENU ON